version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: nexcrm-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nexcrm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zetrez0987
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nexcrm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nexcrm"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: nexcrm-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nexcrm
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Zetrez0987
      JWT_SECRET: DK@Y6HJiob989hh$BVKLbbjb773JuhYgcf67Febnku
    networks:
      - nexcrm-network
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: nexcrm-adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha
    networks:
      - nexcrm-network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  nexcrm-network:
    driver: bridge

volumes:
  postgres-data:

 