spring:
  application:
    name: NexCRM
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nexcrm}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Zetrez0987}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:DK@Y6HJiob989hh$BVKLbbjb773JuhYgcf67Febnku}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    root: INFO
    com.nexcrm: INFO
    org.springframework: WARN 